version: '2'
services:
#  mysql:
#    image: mysql:5.7
#    ports:
#      - 3307:3306
#    volumes:
#      - /mydata/mysql/data:/var/lib/mysql
#      - /mydata/mysql/conf:/etc/mysql
#      - /mydata/mysql/log:/var/log/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD:root
  elasticsearch:
    image: zhengcj01/elasticsearch-with-ik-pinyin:6.6.1
    container_name: elasticsearch
    environment:
      - name=elasticsearch
      - cluster.name=docker-es-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - /mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins
#      - /mydata/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - webservice_web-service

  kibana:
    image: kibana:6.6.1
#    environment:
#      SERVER_NAME: kibana
#      ELASTICSEARCH_URL: http://localhost:9200
    ports:
      - "5601:5601"
    networks:
      - webservice_web-service
#  redis:
#    image: redis:3.2
#    ports:
#      - 6379:6379
#    volumes:
#      - /mydata/redis/data:/data
#    command: redis-server --appendonly yes
#  mongo:
#    image: mongo:3.2
#    ports:
#      - 27017:27017
#    volumes:
#      - /mydata/mongo/db:/data/db
#  nginx:
#    image: nginx:1.10
#    ports:
#      - 80:80
#    volumes:
#      - /mydata/nginx/html:/usr/share/nginx/html
#      - /mydata/nginx/logs:/var/log/nginx
#      - /mydata/nginx/conf:/etc/nginx
networks:
  webservice_web-service:
    external: true