version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./instance/html:/usr/share/nginx/html
      - ./instance/logs:/var/log/nginx
#      - ./instance/conf:/etc/nginx
