version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:80
#    volumes:
#      - ./instance/usr/share/nginx/html:/usr/share/nginx/html
#      - ./instance/etc/nginx:/etc/nginx
#      - ./instance/log:/var/log/nginx
