version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./instance/data:/var/lib/mysql"
      - "./instance/conf:/etc/mysql"
      - "./instance/log:/var/log/mysql"
      - "./instance/init/create:/docker-entrypoint-initdb.d/:ro"
      - "./instance/init/start:/tmp/mysql/init"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
#      MYSQL_USER: "test"
#      MYSQL_PASSWORD: "test"
#    command: mysqld --init-file="/tmp/mysql/init/init.sql"
#    network_mode: "host"
