version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
#    volumes:
#      - "./instance/data/db:/data/db"
#      - "./instance/data/configdb:/data/configdb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_123

  # 如果不需要MongoDB的网页端，以下内容可以不加
#  mongo-express:  # 会自动从Docker Hub上自动获取mongo-express这个镜像
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:  #这里只能使用与上方MONGO_INITDB_ROOT_USERNAME相同的root账号
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root_123
